baseurl = "http://tjbarbour.github.io"
languageCode = "en-us"
title = "T.J. Barbour"
theme = "startbootstrap-clean-blog"
copyright = "The information in this weblog is provided \"AS IS\" with no warranties, and confers no rights.  This weblog does not represent the thoughts, intentions, plans or strategies of my employer. It is solely my opinion."

[author]
  name = "T.J. Barbour"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "My Personal Website & Blog<br/>OLO"
  Author = "T.J. Barbour"
  email = "tjbarbour@gmail.com"
  Ganalytics = "XX-00000000-0"
  
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/tjbarbour"
[[params.social]]
  title = "github"
  url = "https://github.com/tjbarbour"
[[params.social]]
  title = "stack-overflow"
  url = "http://stackoverflow.com/users/37207/tjb"
[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/tjbarbour"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -180
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
 [[menu.main]]
  name = "Resume"
  url = "https://db.tt/WDJDKIqM"
  weight = -180